### ISSUE TITLE
[Frontend] 추가적으로 설치해야 하는 패키지의 추가 관련

### ISSUE THREAD

**Issue by BlaCkinkGJ** [I-O-Benchmark-On-Container/ContainerTracer#21]
현재 `.travis.yml`과 `README.md`에 추가된 패키지에 대해서 기술되어 있지 않아서 빌드 오류가 발생하고 있는 것을 [관련 링크](https://travis-ci.org/github/I-O-Benchmark-On-Container/ContainerTracer/jobs/717856828)를 통해 확인할 수 있습니다.

제가 추가할 수 있도록 관련 내용 올려주시길 바랍니다.

**Comment by dirmathfl** [comment]
```yaml
- language: python
  python: 3.6
  addons:
      apt:
        update: true
        packages:
          - python3-pip
  before_script:
  - pip3 install flask
  - pip3 install flask_socketio
  - cd web
  script:
  - python unit-test.py
```

기존의 `travis.yml` 12번 라인에 `flask_restful`이 아닌 `flask_socketio`로 변경하면 오류가 해결 될 것 같습니다.
